//! CLI commands for the statistical trading engine.

pub mod approve_allowances;
pub mod arbitrage_bot;
pub mod backfill_funding;
pub mod clob_timing;
pub mod backfill_ohlcv;
pub mod backfill_signals;
pub mod binary_backtest;
pub mod calculate_returns;
pub mod check_depth;
pub mod collect_polymarket;
pub mod collect_signals;
pub mod cross_arbitrage;
pub mod cross_market_auto;
pub mod cross_market_backtest;
pub mod directional_auto;
pub mod directional_settle;
pub mod cross_market_scanner;
pub mod cross_market_settle;
pub mod data_status;
pub mod entry_strategy_sim;
pub mod gabagool_auto;
pub mod gabagool_monitor;
pub mod latency_monitor;
pub mod phase1_arbitrage;
pub mod polymarket_paper_trade;
pub mod preflight;
pub mod redeem_positions;
pub mod test_order;
pub mod validate_signals;
pub mod window_timing;

pub use approve_allowances::{run as run_approve_allowances, ApproveAllowancesArgs};
pub use arbitrage_bot::{run_arbitrage_bot, ArbitrageBotArgs};
pub use clob_timing::{run as run_clob_timing, ClobTimingArgs};
pub use backfill_funding::{run_backfill_funding, BackfillFundingArgs};
pub use backfill_ohlcv::{run_backfill_ohlcv, BackfillOhlcvArgs};
pub use backfill_signals::{run_backfill_signals, BackfillSignalsArgs};
pub use binary_backtest::{run_binary_backtest, BinaryBacktestArgs};
pub use calculate_returns::{run_calculate_returns, CalculateReturnsArgs};
pub use collect_polymarket::{run_collect_polymarket, CollectPolymarketArgs};
pub use check_depth::{run as run_check_depth, CheckDepthArgs};
pub use collect_signals::{run_collect_signals, CollectSignalsArgs};
pub use cross_arbitrage::{run_cross_arbitrage, CrossArbitrageArgs};
pub use cross_market_auto::{run as run_cross_market_auto, CrossMarketAutoArgs};
pub use directional_auto::{run as run_directional_auto, DirectionalAutoArgs};
pub use directional_settle::{run as run_directional_settle, DirectionalSettleArgs};
pub use cross_market_backtest::{run as run_cross_market_backtest, CrossMarketBacktestArgs};
pub use cross_market_scanner::{run as run_cross_market_scanner, CrossMarketScannerArgs};
pub use cross_market_settle::{run as run_cross_market_settle, CrossMarketSettleArgs};
pub use data_status::{run_data_status, DataStatusArgs};
pub use entry_strategy_sim::{run_entry_strategy_sim, EntryStrategySimArgs};
pub use gabagool_auto::{run as run_gabagool_auto, GabagoolAutoArgs};
pub use gabagool_monitor::{run as run_gabagool_monitor, GabagoolMonitorArgs};
pub use latency_monitor::{run as run_latency_monitor, LatencyMonitorArgs};
pub use phase1_arbitrage::{run_phase1_arbitrage, Phase1ArbitrageArgs};
pub use polymarket_paper_trade::{run_polymarket_paper_trade, PolymarketPaperTradeArgs};
pub use preflight::{run as run_preflight, PreflightArgs};
pub use redeem_positions::{run as run_redeem_positions, RedeemPositionsArgs};
pub use test_order::{run as run_test_order, TestOrderArgs};
pub use validate_signals::{run_validate_signals, ValidateSignalsArgs};
